package resources;

import service.ReportGenerator;

import javax.swing.*;
import java.awt.*;
import java. awt.event.*;
import java.io.*;

public class ReportGUI extends JFrame {

    // GUI COMPONENTS - These are bound from the .form file
    private JComboBox<String> studentDropdown;
    private JButton generateButton;
    private JLabel titleLabel;
    private JLabel selectLabel;
    private JLabel statusLabel;
    private JPanel mainPanel;

    private ReportGenerator reportGen;

    private static final String STUDENT_FILE = "data/student_information.csv";

    public ReportGUI() {
        // $$$setupUI$$$() is auto-generated by IntelliJ GUI Designer
        // If not using the GUI Designer's automatic generation, call it manually:
        $$$setupUI$$$();

        setTitle("Academic Performance Report Generator");
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame. EXIT_ON_CLOSE);
        setContentPane(mainPanel);

        reportGen = new ReportGenerator();
        studentDropdown. addItem("-- Select a student --");

        loadStudents();

        generateButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                generateReport();
            }
        });
    }

    // LOAD STUDENTS METHOD from CSV files
    private void loadStudents() {
        try (BufferedReader reader = new BufferedReader(new FileReader(STUDENT_FILE))) {
            String line;
            reader.readLine();

            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");

                if (data. length < 3) {
                    continue;
                }

                String studentID = data[0];
                String firstName = data[1];
                String lastName = data[2];
                String fullName = firstName + " " + lastName;
                String displayText = studentID + " - " + fullName;

                studentDropdown.addItem(displayText);
            }

            int studentCount = studentDropdown. getItemCount() - 1;
            statusLabel.setText("Status:  Loaded " + studentCount + " students");

        } catch (FileNotFoundException e) {
            statusLabel.setText("Status: Error - Student file not found!");
            JOptionPane.showMessageDialog(this,
                    "Could not find student_information.csv file.\n" +
                            "Please make sure the data folder exists.",
                    "File Not Found",
                    JOptionPane.ERROR_MESSAGE);

        } catch (IOException e) {
            statusLabel.setText("Status: Error - Could not read file!");
            JOptionPane. showMessageDialog(this,
                    "Error reading student file: " + e.getMessage(),
                    "Read Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void generateReport() {
        int selectedIndex = studentDropdown. getSelectedIndex();

        if (selectedIndex == 0) {
            statusLabel.setText("Status: Please select a student first!");
            JOptionPane.showMessageDialog(this,
                    "Please select a student from the dropdown list before generating a report.",
                    "No Student Selected",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String selectedItem = (String) studentDropdown.getSelectedItem();

        if (selectedItem == null || ! selectedItem.contains(" - ")) {
            statusLabel.setText("Status: Invalid selection!");
            JOptionPane.showMessageDialog(this,
                    "Invalid selection.  Please select a valid student.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] parts = selectedItem.split(" - ");
        String studentID = parts[0];

        try {
            statusLabel.setText("Status: Generating report for " + studentID + "...");

            reportGen.generatePDF(studentID);

            statusLabel. setText("Status: Report generated successfully!");

            String successMessage = "PDF Report generated successfully!\n\n" +
                    "Student: " + selectedItem + "\n" +
                    "Saved to: data/report/" + studentID + "_Report.pdf";

            JOptionPane. showMessageDialog(this,
                    successMessage,
                    "Success! ",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            statusLabel.setText("Status: Error generating report!");

            String errorMessage = "Sorry, there was a problem generating the report.\n\n" +
                    "Error: " + e. getMessage() + "\n\n" +
                    "Please try again or contact support. ";

            JOptionPane.showMessageDialog(this,
                    errorMessage,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            e.printStackTrace();
        }
    }

    // This method is generated by IntelliJ GUI Designer
    // It reads the .form file and initializes all bound components
    private void $$$setupUI$$$() {
        // IntelliJ IDEA will auto-generate this method when you build the project
        // The generated code will create and configure all components defined in the .form file
    }

    // MAIN METHOD
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReportGUI gui = new ReportGUI();
                gui.setVisible(true);
            }
        });
    }
}
