#CRS User Preferences
#Thu Jul 09 16:28:02 MYT 2026
last_email=CA001

#SMTP settings for email notifications
smtp_host=smtp.gmail.com
smtp_port=587
smtp_username=taichi.ihciat@gmail.com
smtp_password=hlptamkihphoubmg
